//
//  Participant.swift
//  Assignment1
//


protocol Participant {
    init(name: String)
    func completionTime(for sport: Sport, in triathlon: Triathlon, randomValue value: Double) -> Int
    
    var name: String { get }
    
    var favoriteSport: Sport? { get }
    
}

extension Participant {
    
    /// metersPerMinute function circulate the speed according to given logic in assignemtn
    /// - Parameters:
    ///   - sport: sport type
    ///   - double: random value give to the function
    /// - Returns: simulated spped generated by this function
    func metersPerMinute(for sport: Sport, randomValue double: Double = Double.random(in: 0 ..< 1.0)) -> Int {
        
        var value: Double
        switch sport {
        case .swimming:
            value = 43
        case .cycling:
            value = 500
        case .running:
            value = 157
        }
        
        var modifier = 0.8 + (double * 0.4)
        if let favoriteSport = self.favoriteSport {
            if favoriteSport == sport {
                modifier += 0.08
            }
            else {
                modifier -= 0.08
            }
        }
        
        return Int(value * modifier)
        
    }
    
    
    func completionTime(for sport: Sport, in triathlon: Triathlon) -> Int {
        let result = completionTime(for: sport, in: triathlon, randomValue: Double.random(in: 0 ..< 1.0))
        return result
    }
    
    
    func completionTime(for sport: Sport, in triathlon: Triathlon, randomValue value: Double) -> Int {
        return triathlon.distance(for: sport) / metersPerMinute(for: sport, randomValue: value)
    }
}
